"""
The `GLLVMBitcodeExtract` action.
"""

import logging
import os
import tempfile
from pathlib import Path
from typing import Dict

from blight.action import CompilerAction
from blight.enums import Lang
from blight.tool import CompilerTool, Tool

logger = logging.getLogger(__name__)


class GLLVMBitcodeExtract(CompilerAction):
    """
    Compile and extract bitcode with GLLVM.
    """

    def __init__(self, config: Dict[str, str]):
        self._bc_dir = tempfile.mkdtemp()
        super().__init__(config)

    def before_run(self, tool: CompilerTool) -> None:  # type: ignore
        if tool.lang in [Lang.C, Lang.Cxx]:
            os.environ.update(
                {
                    "BLIGHT_WRAPPED_CC": "gclang",
                    "BLIGHT_WRAPPED_CXX": "gclang++",
                    # NOTE(sonya): both WLLVM and GLLVM use WLLVM_BC_STORE
                    "WLLVM_BC_STORE": str(self._bc_dir),
                }
            )

            # Update the environment so WLLVM_BC_STORE is defined
            tool._env = tool._fixup_env()
        else:
            logger.debug("not extracting bitcode for an unknown language")

    def after_run(self, tool: Tool, *, run_skipped: bool = False):
        # Move bc file to cwd and add .bc suffix
        # File prefix is autogenerated as the hash of the path to the original bitcode file by gllvm
        bc_file = os.listdir(self._bc_dir)[0]
        old_path = Path(self._bc_dir) / bc_file
        old_path.rename(tool.cwd / (bc_file + ".bc"))
